# auth-service/src/main/resources/application.yml
server:
  port: 8081

spring:
  application:
    name: auth-service

  # This is for direct configuration, but we'll use config server in production
  datasource:
    url: jdbc:postgresql://moniebank:5432/moniebank
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: emailnotification:com.maxiflexy.auth_service.dto.EmailNotificationDto

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/auth/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: my_very_confidential_sectet_for_auth_application_with_sufficient_length_for_security
    accessTokenExpirationMsec: 300000 # 5 minutes (5 * 60 * 1000)
    refreshTokenExpirationMsec: 1200000 # 20 minutes (20 * 60 * 1000)
    verification:
      token-expiry-minutes: 60 # 1 hour
  frontend:
    base-url: http://localhost:80/
  # Cookie security settings
  cookie:
    secure: false # Set to true in production with HTTPS
  # REMOVE CORS settings - API Gateway handles CORS

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'