server:
  port: 8083

spring:
  application:
    name: notification-service

  # MailDev Configuration (replacing Gmail)
  mail:
    host: maildev
    port: 1025
    # No username/password needed for MailDev
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  # Kafka Configuration
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Additional consumer properties for better reliability
      enable-auto-commit: true
      auto-commit-interval: 1000
      session-timeout: 30000
      heartbeat-interval: 3000
      # Retry configuration
      max-poll-records: 10
      max-poll-interval: 300000
    # Add producer configuration if needed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Eureka configuration
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Logging configuration for debugging
logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    com.maxiflexy.notification_service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"