server:
  port: 8083

spring:
  application:
    name: notification-service
#  config:
#    import: optional:configserver:http://localhost:8888

  # MailDev Configuration (replacing Gmail)
  mail:
    host: maildev
    #host: 16.171.9.59
    port: 1025
    # No username/password needed for MailDev
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  # Kafka Configuration
  kafka:
    bootstrap-servers: kafka:9092
    #bootstrap-servers: 16.171.9.59:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Eureka configuration
#eureka:
#  instance:
#    hostname: localhost
#    preferIpAddress: false
#    instanceId: localhost:${spring.application.name}:${server.port}
#    appname: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/


# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'