server:
  port: 8083

spring:
  application:
    name: notification-service
#  config:
#    import: optional:configserver:http://localhost:8888

  # Gmail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.maxiflexy.notification_service.dto,com.maxiflexy.transaction_service.dto,com.maxiflexy.account_service.dto

# Eureka configuration
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    instanceId: localhost:${spring.application.name}:${server.port}
    appname: ${spring.application.name}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'