services:

  moniebank:
    image: postgres:17-alpine
    container_name: moniebank
    environment:
      POSTGRES_DB: moniebank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - account-data:/var/lib/postgresql/data
    networks:
      - banking-network

#  # PostgreSQL databases for each service
#  account-db:
#    image: postgres:17-alpine
#    container_name: account-db
#    environment:
#      POSTGRES_DB: account_service
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5433:5432"
#    volumes:
#      - account-data:/var/lib/postgresql/data
#    networks:
#      - banking-network
#
#  auth-db:
#    image: postgres:17-alpine
#    container_name: auth-db
#    environment:
#      POSTGRES_DB: auth_service
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5434:5432"
#    volumes:
#      - auth-data:/var/lib/postgresql/data
#    networks:
#      - banking-network

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - banking-network
    depends_on:
      #- account-db
      #- auth-db
      - moniebank

  # Kafka and Zookeeper for messaging
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - banking-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - banking-network

  # MailDev for email testing
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"  # Web interface
      - "1025:1025"  # SMTP port
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  account-data:
  auth-data: