server:
  port: 8084

spring:
  application:
    name: transaction-service
#  config:
#    import: optional:configserver:http://localhost:8888

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/account_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Eureka configuration
eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    instanceId: localhost:${spring.application.name}:${server.port}
    appname: ${spring.application.name}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'