# api-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "http://localhost:8080"
              - "http://localhost"
              - "http://localhost:80"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            # CRITICAL: Must be true for cookies to work
            allowCredentials: true
            maxAge: 3600
            # Expose auth error headers to frontend
            exposedHeaders:
              - "X-Auth-Error"

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Token secret for JWT validation
app:
  auth:
    tokenSecret: my_very_confidential_sectet_for_auth_application_with_sufficient_length_for_security

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/