# api-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"      # Browser normalizes :80 to this
              - "http://localhost:80"   # Explicit port 80
              - "http://127.0.0.1"      # Alternative localhost
              - "http://127.0.0.1:80"   # Alternative with port
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowedHeaders:
              - "*"
            # CRITICAL: Must be true for cookies to work
            allowCredentials: true
            maxAge: 3600
            # Expose auth error headers to frontend
            exposedHeaders:
              - "X-Auth-Error"
              - "Set-Cookie"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"

management:
  endpoints:
    web:
      exposure:
        include: '*'

# Token secret for JWT validation
app:
  auth:
    tokenSecret: my_very_confidential_sectet_for_auth_application_with_sufficient_length_for_security

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/