server:
  port: 8082

spring:
  application:
    name: account-service
#  config:
#    import: optional:configserver:http://localhost:8888

  datasource:
    #url: jdbc:postgresql://localhost:5433/account_service
    #url: jdbc:postgresql://localhost:5433/moniebank
    url: jdbc:postgresql://34.38.26.110:5432/moniebank
    #username: postgres
    username: moniebank-db
    #password: password
    password: password1234#
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method


# Eureka configuration
#eureka:
#  instance:
#    hostname: localhost
#    preferIpAddress: false
#    instanceId: localhost:${spring.application.name}:${server.port}
#    appname: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
