server:
  port: 8082

spring:
  application:
    name: account-service

  # Database configuration using environment variables
  datasource:
    url: jdbc:postgresql://moniebank:5432/${POSTGRES_DB:moniebank}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Encryption configuration
app:
  encryption:
    secret-key: ${ENCRYPTION_SECRET_KEY}

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'