server:
  port: 8761

spring:
  application:
    name: eureka-server
#  config:
#    import: optional:configserver:http://localhost:8888

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#
#  instance:
#    hostname: localhost
#    preferIpAddress: false


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    hostname: eureka-service
    preferIpAddress: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
